PK2237A5/Controllers/ActorController.cs
using Antlr.Runtime.Misc;
using PK2237A5.Data;
using PK2237A5.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PK2237A5.Controllers
{
    public class ActorController : Controller
    {
        public Manager m = new Manager();

        // GET: Actor
        public ActionResult Index()
        {
            var actor = m.ActorGetAll();
            return View(actor);
        }

        // GET: Actor/Details/5
        public ActionResult Details(int? id)
        {

            var actor = m.ActorGetByIdWithDetail(id.GetValueOrDefault());
            if (actor == null)
            {
                return HttpNotFound();
            }
            else
            {
                return View(actor);
            }

        }

        // GET: Actor/Create
        [Authorize(Roles = "Executive")]
        public ActionResult Create()
        {
            var actor = new ActorAddViewModel();

            actor.Executive = User.Identity.Name;
            return View(actor);
        }

        // POST: Actor/Create
        [HttpPost]
        public ActionResult Create(ActorAddViewModel newItem)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(newItem);
                }

                var addedItem = m.ActorAdd(newItem);

                if (addedItem == null)
                {
                    return View(newItem);
                }

                else
                {
                    return RedirectToAction("Details", new { id = addedItem.Id });
                }
            }
            catch
            {
                return View();
            }
        }


        [Authorize(Roles = "Coordinator")]
        [Route("Actor/{id}/AddShow")]
        [HttpGet]
        
        public ActionResult AddShow(int? id)
        {

            var a = m.ActorGetById(id.GetValueOrDefault());

            if (a == null)
            {
                return HttpNotFound();
            }

            else
            {
               
                var o = new ShowAddFormViewModel();
                o.Coordinator = User.Identity.Name;
                o.ActorId = a.Id;
                o.ActorsName = a.Name;

                o.GenresList = new SelectList(m.GenreGetAll(), "Name", "Name");

                var selectedActor = new List<int> { a.Id };
                o.ActorsList = new MultiSelectList(m.ActorGetAll(), "Id", "Name", selectedActor);

                return View(o);
            }
        }

        [Authorize(Roles = "Coordinator")]
        [HttpPost]
        [Route("Actor/{id}/AddShow")]
        [ValidateInput(false)]
        public ActionResult AddShow(ShowAddViewModel newItem)
        {
            
            if (!ModelState.IsValid)
            {
                return View(newItem);
            }

            var addedItem = m.ShowAdd(newItem);

            if (addedItem == null)
            {
                return View(newItem);
            }
            else
            {
                return RedirectToAction("Details", "Show", new { id = addedItem.Id });
            }
        }



    }
}

PK2237A5/Controllers/GenreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PK2237A5.Controllers
{
    public class GenreController : Controller
    {
        public Manager m = new Manager();

        // GET: Genre
        public ActionResult Index()
        {
            var genre = m.GenreGetAll();
            return View(genre);
        }

        
    }
}

PK2237A5/Controllers/ShowController.cs
using PK2237A5.Data;
using PK2237A5.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PK2237A5.Controllers
{
    public class ShowController : Controller
    {
        public Manager m = new Manager();

        // GET: Show
        public ActionResult Index()
        {
            var show = m.ShowGetAll();
            return View(show);
        }

        // GET: Show/Details/5
        public ActionResult Details(int? id)
        {
            var show = m.ShowGetByIdWithDetail(id.GetValueOrDefault());

            if (show == null)
            {
                return HttpNotFound();
            }
            else
            {
                // Pass the object to the view
                return View(show);
            }
        }
        [Authorize(Roles = "Clerk")]
        [Route("Show/{id}/AddEpisode")]
        [HttpGet]

        public ActionResult AddEpisode(int? id)
        {

            var s = m.ShowGetByIdWithDetail(id.GetValueOrDefault());

            if (s == null)
            {
                return HttpNotFound();
            }

            else
            {

                var e = new EpisodeAddFormViewModel();
                e.Clerk = User.Identity.Name;
                e.ShowId = s.Id;
                e.ShowName = s.Name;

                e.GenresList = new SelectList(m.GenreGetAll(), "Name", "Name");

                return View(e);
            }
        }

        [Authorize(Roles = "Clerk")]
        [HttpPost]
        [Route("Show/{id}/AddEpisode")]
        [ValidateInput(false)]
        public ActionResult AddEpisode(EpisodeAddViewModel newItem)
        {

            if (!ModelState.IsValid)
            {
                return View(newItem);
            }

            // Process the input
            var addedItem = m.EpisodeAdd(newItem);

            if (addedItem == null)
            {
                return View(newItem);
            }
            else
            {
                return RedirectToAction("Details", "Episode", new { id = addedItem.Id });
            }
        }

    }
}

PK2237A5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title - PK2237A5</title>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="PK2237A5" />
    <meta name="application-name" content="2237-92ac95cd-9559-4079-8c98-bd8351374cc7" />

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @{
        var RequestUser = new PK2237A5.Controllers.RequestUser(User as System.Security.Claims.ClaimsPrincipal);
    }

</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("PK2237A5", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Genres", "Index", "Genre", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Actors", "Index", "Actor", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Shows", "Index", "Show", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Episodes", "Index", "Episode", new { area = "" }, new { @class = "nav-link" })</li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="loadDataDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Load Data
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="loadDataDropdown">
                            <li>@Html.ActionLink("Roles", "Roles", "LoadData", new { area = "" }, new { @class = "dropdown-item" })</li>
                            @if (RequestUser.IsAuthenticated)
                            {
                                <li>@Html.ActionLink("Genres", "Genres", "LoadData", new { area = "" }, new { @class = "dropdown-item" })</li>
                                <li>@Html.ActionLink("Actors", "Actors", "LoadData", new { area = "" }, new { @class = "dropdown-item" })</li>
                                <li>@Html.ActionLink("Shows", "Shows", "LoadData", new { area = "" }, new { @class = "dropdown-item" })</li>
                                <li>@Html.ActionLink("Episodes", "Episodes", "LoadData", new { area = "" }, new { @class = "dropdown-item" })</li>
                            }
                        </ul>
                    </li>
                </ul>

                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>
                <small>
                    By submitting this assignment you agree to the following:
                    I declare that this assignment is my own work in accordance with the Seneca Academic
                    Policy. No part of this assignment has been copied manually or electronically from
                    any other source (including web sites) or distributed to other students.
                </small>
            </p>
            <p>&copy; Panchanok Kaewchinda, kpanchanok@myseneca.ca, WEB524, Fall 2023</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>

    @RenderSection("scripts", required: false)
</body>
</html>